# numpy practice session

In [1]:
import numpy as np # in the staret of this line, left of this box we can see the [1] which means this library has been imported

# Creating an array using numpy 

In [2]:
food= np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
num= np.array([5,4,3])
num

array([5, 4, 3])

In [4]:
len(food)

3

In [5]:
len(num)

3

In [6]:
type(food)

numpy.ndarray

In [7]:
type(num)

numpy.ndarray

In [8]:
food[2]  # indexing 

'raita'

In [10]:
num[1] # indexing

4

In [12]:
num.mean()  # we can use any property from the list of name. by pressing tab button e.g. mean here

4.0

In [14]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# empty array
np.empty(5)

array([1., 1., 1., 1., 1.])

In [17]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
np.linspace(2,40,10)   #equally spaced numbers

array([ 2.        ,  6.22222222, 10.44444444, 14.66666667, 18.88888889,
       23.11111111, 27.33333333, 31.55555556, 35.77777778, 40.        ])

In [24]:
np.linspace(5,50,num=10)     # last element denotes the number of elements in the array

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [25]:
# specifying your data type
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [27]:
# specifying your data type
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array funtions

In [28]:
a= np.array([1,2,3,2.5,3,5,3,0.5])
a

array([1. , 2. , 3. , 2.5, 3. , 5. , 3. , 0.5])

In [30]:
a.sort()
a

array([0.5, 1. , 2. , 2.5, 3. , 3. , 3. , 5. ])

In [31]:
b=np.array([1,2,3,4,0.7,1,0.9])
b

array([1. , 2. , 3. , 4. , 0.7, 1. , 0.9])

In [34]:
c=np.concatenate((a,b))
c

array([0.5, 1. , 2. , 2.5, 3. , 3. , 3. , 5. , 1. , 2. , 3. , 4. , 0.7,
       1. , 0.9])

In [36]:
c.sort()
c

array([0.5, 0.7, 0.9, 1. , 1. , 1. , 2. , 2. , 2.5, 3. , 3. , 3. , 3. ,
       4. , 5. ])

# 2-D arrays

In [37]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
b= np.array([[3,4,5],[8,7,6]])
b

array([[3, 4, 5],
       [8, 7, 6]])

In [50]:
c= np.concatenate((a,b), axis=0)
c                             # make sure the dimensions of both arrays are same. 
                           #In case of different dimensions we define the axis which comes later on

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [8, 7, 6]])

In [52]:
c= np.concatenate((a,b), axis=1)         # axis changed 
c 

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 8, 7, 6]])

In [55]:
# n-dimensional array   #tensor

a= np.array([[[0,1,2,3],[4,5,6,7]],
            [[0,1,2,3],[4,5,6,7]],
             [[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [56]:
#dimensions of 3D array

a.ndim

3

In [58]:
b=np.array([[1,2,3],
           [2,3,4],
           [5,6,7]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [59]:
b.ndim

2

In [61]:
#size (# of elements)
np.size(a)     #total number of elements in the array a

24

In [63]:
np.shape(a)     # first element is the no. of matrices, second element is no. of rows in each matrix and last one is coloms

(3, 2, 4)

In [66]:
# reshaping converts an array to the specified form
d= np.array([1,2,3,4,5,6])
d

array([1, 2, 3, 4, 5, 6])

In [72]:
e=d.reshape(2,3)         #2 rows and 3 coloms, but make sure the total number of elements in the array equals 
                      #the size the desired matrix
e

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
#reshaping to the row vector
np.reshape(e, newshape=(1,6), order='C')    #C order takes elements row-wise while F (fortran) takes colom wise

array([[1, 2, 3, 4, 5, 6]])

In [76]:
np.reshape(e, newshape=(1,6), order='F')

array([[1, 4, 2, 5, 3, 6]])

In [77]:
#converting to 2-D arrays
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a.shape    #it shows one dimension only in the output

(9,)

In [80]:
#converting to 2D array
b= a[np.newaxis,:]
b                  # we can observe the two axis by looking at the double square brackets below

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
# now checking its shape
b.shape    # we can see a two dimensional array, but its not visible from the array itself

(1, 9)

In [82]:
# colom-wise conversion
c= a[:, np.newaxis]
c   

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [110]:
data= np.array([1,2,3])
data
data[0]
data[:3]

array([1, 2, 3])

In [112]:
a= np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [113]:
print(a[a<5])

[1 2 3 3 4 4]


In [114]:
print(a[a>=5])

[5 5 6]


In [115]:
print(a[a%2==0])

[2 4 4 6]


In [123]:
print(a[(a>5)|(a==5)])

[5 5 6]


In [124]:
print((a>5)|(a==5))

[[False False False]
 [False False  True]
 [False  True  True]]


In [126]:
a= np.array([[0,1,2],[2,3,4],[5,4,6]])
a

array([[0, 1, 2],
       [2, 3, 4],
       [5, 4, 6]])

In [128]:
b=np.nonzero(a<3)
b

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [130]:
list_of_coordinates= list(zip(b[0],b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(1, 0)


In [93]:
x= [1,2,3,4,5]
y=['a','b','c','d','e']

print(list(zip(x,y)))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]


In [132]:
a= np.nonzero(30)
a

(array([0], dtype=int64),)

In [133]:
a= np.array([[1,2],[2,3]], dtype= complex)
a

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j]])

In [135]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [136]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [137]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [138]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [143]:
np.arange(1,4,2)

array([1, 3])

In [145]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [146]:
a= np.array([[1,2],[4,3]])
a

array([[1, 2],
       [4, 3]])

In [149]:
b=np.asmatrix(a)
b[0,0]=7
b

matrix([[7, 2],
        [4, 3]])

In [156]:
np.array(np.mat('1 2 3;4 3 2'), subok=False)

array([[1, 2, 3],
       [4, 3, 2]])

In [157]:
np.array(np.mat('1 2 3;4 3 2'), subok=True)

matrix([[1, 2, 3],
        [4, 3, 2]])

In [169]:
a= np.empty([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [170]:
np.empty_like(a) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [175]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [177]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [179]:
np.full([3,2],4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [182]:
np.asanyarray('a')

array('a', dtype='<U1')

In [184]:
np.ascontiguousarray(a,dtype= np.int64)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [186]:
c=np.copy(a)
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [189]:
# random number generators
rng= np.random.default_rng(12345)
rints= rng.integers(low=3, high=7, size=5)
rints

array([5, 3, 6, 4, 3], dtype=int64)

In [193]:
rng= np.random.default_rng(seed=12)
print(rng)
array1= rng.random((3,4))
array1

Generator(PCG64)


array([[0.25082446, 0.94675294, 0.18932038, 0.17929141],
       [0.34988924, 0.23054125, 0.67044574, 0.11507938],
       [0.89630937, 0.85813049, 0.00282703, 0.54146616]])

In [196]:
a= np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [197]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [198]:
c= a.dot(b)
c

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [199]:
c=a*b
c

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [200]:
c=a@b
c

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [208]:
rg=np.random.default_rng((2,3))
a=rg.random((2,3))
a

array([[0.35144692, 0.50708123, 0.53848232],
       [0.16973393, 0.06648618, 0.58651797]])

In [210]:
a.sum()
a.min()
a.max()

0.5865179698087197

In [211]:
b= np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [212]:
b.sum(axis=0)

array([ 9, 12, 15])

In [213]:
b.sum(axis=1)

array([ 3, 12, 21])

In [214]:
b.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [3]:
# Indexing, slicing and iterating 
import numpy as np
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a=a**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [5]:
a[2]

8

In [6]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [8]:
a[:6:2]=1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [14]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [15]:
for i in a:
    print(i**(1/3))    # I'm alittel confused as the 1/3 power of 729 shpould result in 9 but it's 8.9999

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [18]:
c=729
c**(1/3)

8.999999999999998

In [24]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [29]:
def f(x, y):
    return 5 * x + y                  # here x and y are representing the coodinates like (x,y)= [(0,0), (0,1), (0,2)...]

b = np.fromfunction(f, (2, 3), dtype=int)
b

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [31]:
b[2,3]

23

In [32]:
b[0:5,2]

array([ 2, 12, 22, 32, 42])

In [33]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [35]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [36]:
b[-1]

array([40, 41, 42, 43])

In [37]:
b[:,-1]

array([ 3, 13, 23, 33, 43])

In [38]:
c= np.array([[[1,2,3],[4,5,6]],
             [[2,3,1],[5,4,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 1],
        [5, 4, 6]]])

In [40]:
c.shape

(2, 2, 3)

In [42]:
c[1,...]   # it is similar to c[1,:,:] that results in first matrix

array([[2, 3, 1],
       [5, 4, 6]])

In [44]:
c[...,1]   # all matrices, all rows and second coloms data

array([[2, 5],
       [3, 4]])

In [45]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [50]:
for element in b.flat:

    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Indexing through arrays


In [51]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x[2]

2

In [53]:
x[-2]

8

In [56]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
x[1,3]

8

In [58]:
x[1,-1]

9

In [60]:
x[0][2] #it is similar to the x[0,2]= x[0][2]

2

In [61]:
x=np.array([[[1],[2],[3]],[[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [62]:
x.shape

(2, 3, 1)

In [68]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [ ]:
import numpy as np
import os
import yaml
from types import Simplenamespace as SN

class Multiproduct():
    def __int__(self, n_machine, n_buffer, n_prod, cycle_time, time_step, boundary_capacity):
        self.nm= n_machine
        self.nb= n_buffer
        self.nprod= n_prod
        self.ct= cycle-time
        self.bc= boundary_capacity
        self.ts= time_step
        

In [75]:
import numpy as np

self.ct=[1,2,3]
self.n_machine=size(ct,2)
self.b_ini= [2,3]
self.B=[20,30]
self.n_buffer= size(B,2)

def production (self):
    
    prod= np.zeros(self.n_machine)


for i in range(self.n_machine):
    prod= prod + 1/self.ct
#     bi= prod(i)-prod(i+1)-b_ini(i) 
    return prod

NameError: name 'self' is not defined

In [78]:
def production():
    prod= 1/ct
    ct= production()
    ct(2)
    prod

In [89]:
def my_funtion(name):
    print('this the input:', name)
    
my_funtion('hellp')

this the input: hellp


In [91]:
def country_funtion(country= 'Pakistan'):
    print('I am from' + country)
country_funtion('US')

I am fromUS


In [95]:
def funtion(*stats):
    print(stats)
funtion(1,2,3,4,4,5)

(1, 2, 3, 4, 4, 5)


In [97]:
def line(machine, prod):
    print(machine, prod)
line(prod= 3,machine= 5)


5 3


In [101]:
def sum(m1,m2):
    return m1+m2
production=sum(2,3)
print(production)

5


In [1]:
def count(num):
    if num<=0:
        
    else:
        print(num)
    count(num-1)
    
count(3)

SyntaxError: 'break' outside loop (Temp/ipykernel_8984/69943233.py, line 3)

In [6]:
def square(num):
    return num*num
    
for i in range(1,11):
    print(square(i))

1
4
9
16
25
36
49
64
81
100
